######################################################################
# Automatically generated by qmake (3.0) Sat Jun 24 11:48:11 2017
######################################################################

TEMPLATE = app
TARGET = VI-MEAN
INCLUDEPATH += . /home/mylxiaoyi/source/ros_catkin.lunar/install_isolated/include \
               OpenChisel/chisel_ros/include OpenChisel/open_chisel/include \
               /usr/local/include/pcl-1.8

# Input
HEADERS += feature_tracker/src/feature_tracker.h \
           feature_tracker/src/parameters.h \
           feature_tracker/src/tic_toc.h \
           self_calibration_estimator/src/euler_integration.h \
           self_calibration_estimator/src/feature_manager.h \
           self_calibration_estimator/src/imu_factor.h \
           self_calibration_estimator/src/integration_base.h \
           self_calibration_estimator/src/marginalization.h \
           self_calibration_estimator/src/marginalization_factor.h \
           self_calibration_estimator/src/midpoint_integration.h \
           self_calibration_estimator/src/motion_estimator.h \
           self_calibration_estimator/src/parameters.h \
           self_calibration_estimator/src/pose_local_parameterization.h \
           self_calibration_estimator/src/projection_factor.h \
           self_calibration_estimator/src/RK4_integration.h \
           self_calibration_estimator/src/self_calibration_estimator.h \
           self_calibration_estimator/src/tic_toc.h \
           self_calibration_estimator/src/utility.h \
           self_calibration_estimator/src/visualization.h \
           stereo_mapper/src/calc_cost.h \
           stereo_mapper/src/parameters.h \
           stereo_mapper/src/stereo_mapper.h \
           stereo_mapper/src/tic_toc.h \
           camera_model/include/camodocal/calib/CameraCalibration.h \
           camera_model/include/camodocal/camera_models/Camera.h \
           camera_model/include/camodocal/camera_models/CameraFactory.h \
           camera_model/include/camodocal/camera_models/CataCamera.h \
           camera_model/include/camodocal/camera_models/CostFunctionFactory.h \
           camera_model/include/camodocal/camera_models/EquidistantCamera.h \
           camera_model/include/camodocal/camera_models/PinholeCamera.h \
           camera_model/include/camodocal/camera_models/ScaramuzzaCamera.h \
           camera_model/include/camodocal/chessboard/Chessboard.h \
           camera_model/include/camodocal/chessboard/ChessboardCorner.h \
           camera_model/include/camodocal/chessboard/ChessboardQuad.h \
           camera_model/include/camodocal/chessboard/Spline.h \
           camera_model/include/camodocal/gpl/EigenQuaternionParameterization.h \
           camera_model/include/camodocal/gpl/EigenUtils.h \
           camera_model/include/camodocal/gpl/gpl.h \
           camera_model/include/camodocal/sparse_graph/Transform.h \
           OpenChisel/chisel_ros/include/chisel_ros/ChiselServer.h \
           OpenChisel/chisel_ros/include/chisel_ros/Conversions.h \
           OpenChisel/chisel_ros/include/chisel_ros/Serialization.h \
           OpenChisel/open_chisel/include/open_chisel/Chisel.h \
           OpenChisel/open_chisel/include/open_chisel/Chunk.h \
           OpenChisel/open_chisel/include/open_chisel/ChunkManager.h \
           OpenChisel/open_chisel/include/open_chisel/ColorVoxel.h \
           OpenChisel/open_chisel/include/open_chisel/DistVoxel.h \
           OpenChisel/open_chisel/include/open_chisel/FixedPointFloat.h \
           OpenChisel/open_chisel/include/open_chisel/ProjectionIntegrator.h \
           OpenChisel/open_chisel/include/open_chisel/camera/ColorImage.h \
           OpenChisel/open_chisel/include/open_chisel/camera/DepthImage.h \
           OpenChisel/open_chisel/include/open_chisel/camera/Intrinsics.h \
           OpenChisel/open_chisel/include/open_chisel/camera/PinholeCamera.h \
           OpenChisel/open_chisel/include/open_chisel/geometry/AABB.h \
           OpenChisel/open_chisel/include/open_chisel/geometry/Frustum.h \
           OpenChisel/open_chisel/include/open_chisel/geometry/Geometry.h \
           OpenChisel/open_chisel/include/open_chisel/geometry/Interpolate.h \
           OpenChisel/open_chisel/include/open_chisel/geometry/Plane.h \
           OpenChisel/open_chisel/include/open_chisel/geometry/Raycast.h \
           OpenChisel/open_chisel/include/open_chisel/io/PLY.h \
           OpenChisel/open_chisel/include/open_chisel/marching_cubes/MarchingCubes.h \
           OpenChisel/open_chisel/include/open_chisel/mesh/Mesh.h \
           OpenChisel/open_chisel/include/open_chisel/pointcloud/PointCloud.h \
           OpenChisel/open_chisel/include/open_chisel/threading/Threading.h \
           OpenChisel/open_chisel/include/open_chisel/truncation/ConstantTruncator.h \
           OpenChisel/open_chisel/include/open_chisel/truncation/InverseTruncator.h \
           OpenChisel/open_chisel/include/open_chisel/truncation/QuadraticTruncator.h \
           OpenChisel/open_chisel/include/open_chisel/truncation/Truncator.h \
           OpenChisel/open_chisel/include/open_chisel/weighting/ConstantWeighter.h \
           OpenChisel/open_chisel/include/open_chisel/weighting/Weighter.h
SOURCES += camera_model/src/intrinsic_calib.cc \
           feature_tracker/src/feature_tracker.cpp \
           feature_tracker/src/feature_tracker_node.cpp \
           feature_tracker/src/parameters.cpp \
           self_calibration_estimator/src/feature_manager.cpp \
           self_calibration_estimator/src/integration.cpp \
           self_calibration_estimator/src/marginalization.cpp \
           self_calibration_estimator/src/marginalization_factor.cpp \
           self_calibration_estimator/src/motion_estimator.cpp \
           self_calibration_estimator/src/parameters.cpp \
           self_calibration_estimator/src/pose_local_parameterization.cpp \
           self_calibration_estimator/src/projection_factor.cpp \
           self_calibration_estimator/src/self_calibration_estimator.cpp \
           self_calibration_estimator/src/self_calibration_estimator_node.cpp \
           self_calibration_estimator/src/utility.cpp \
           self_calibration_estimator/src/visualization.cpp \
           stereo_mapper/src/calc_cost.cpp \
           stereo_mapper/src/gpu_test.cpp \
           stereo_mapper/src/parameters.cpp \
           stereo_mapper/src/stereo_mapper.cpp \
           stereo_mapper/src/stereo_mapper_node.cpp \
           camera_model/src/calib/CameraCalibration.cc \
           camera_model/src/camera_models/Camera.cc \
           camera_model/src/camera_models/CameraFactory.cc \
           camera_model/src/camera_models/CataCamera.cc \
           camera_model/src/camera_models/CostFunctionFactory.cc \
           camera_model/src/camera_models/EquidistantCamera.cc \
           camera_model/src/camera_models/PinholeCamera.cc \
           camera_model/src/camera_models/ScaramuzzaCamera.cc \
           camera_model/src/chessboard/Chessboard.cc \
           camera_model/src/gpl/EigenQuaternionParameterization.cc \
           camera_model/src/gpl/gpl.cc \
           camera_model/src/sparse_graph/Transform.cc \
           OpenChisel/chisel_ros/src/ChiselNode.cpp \
           OpenChisel/chisel_ros/src/ChiselServer.cpp \
           OpenChisel/open_chisel/src/Chisel.cpp \
           OpenChisel/open_chisel/src/Chunk.cpp \
           OpenChisel/open_chisel/src/ChunkManager.cpp \
           OpenChisel/open_chisel/src/ColorVoxel.cpp \
           OpenChisel/open_chisel/src/DistVoxel.cpp \
           OpenChisel/open_chisel/src/ProjectionIntegrator.cpp \
           OpenChisel/open_chisel/src/camera/Intrinsics.cpp \
           OpenChisel/open_chisel/src/camera/PinholeCamera.cpp \
           OpenChisel/open_chisel/src/geometry/AABB.cpp \
           OpenChisel/open_chisel/src/geometry/Frustum.cpp \
           OpenChisel/open_chisel/src/geometry/Plane.cpp \
           OpenChisel/open_chisel/src/geometry/Raycast.cpp \
           OpenChisel/open_chisel/src/io/PLY.cpp \
           OpenChisel/open_chisel/src/marching_cubes/MarchingCubes.cpp \
           OpenChisel/open_chisel/src/mesh/Mesh.cpp \
           OpenChisel/open_chisel/src/pointcloud/PointCloud.cpp \
    stereo_mapper/src/stereo_mapper_test_node.cpp
